[Feat] Search and Filter Base Review Page
uwblueprint/ccbc pull request #147
Opened 2022-07-22 03:47 UTC by jessiiepeng

## Notion ticket link

[Search and Filter Base Review Page](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=169bc7491da340a9876892d52841247f)

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have run docker-compose up and my project compiled
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-24 23:41 UTC, susheelk requested changes
Nice work! The url changing seems to work as desired :slightly_smiling_face: 

Just a couple of minor comments:
* This wasn't part of this ticket, but hitting enter on the search bar doesn't submit. Could you please add this to your PR?
* There doesn't seem to be any spacing at the bottom of the page:
![image](https://user-images.githubusercontent.com/19916973/180670375-660e9cdf-3349-474d-ae06-ac3dca5f9b0f.png)
We probably want to add some for readability 

Thanks!

2022-07-24 23:41 UTC, susheelk commented on frontend/src/components/pages/SearchReviews/SearchReviews.tsx
> +    const params = new URLSearchParams(window.location.search);
Could you document these search params? (ie what each of them are, what they do, some examples, etc). You could maybe put it in the component header

2022-07-24 23:41 UTC, susheelk commented on frontend/src/components/pages/SearchReviews/SearchReviews.tsx
> +      searchText || genresFilter.length > 0 || ageRangeFilter.length > 0
You might run into weird issues with embedding (ie when using special characters, etc) when building the URL like this. I'd suggest looking into JS's built in url library: https://www.valentinog.com/blog/url/

2022-07-24 23:41 UTC, susheelk commented on frontend/src/components/pages/SearchReviews/SearchReviews.tsx
> +    let newSearchUrl = "/magazine/search_results";
I would suggest moving this URL generation code into a separate helper function (ie one that takes search text, filters as arguments and returns a generated URL). In the future, we'll have other parts of our code also generating URLs and redirecting to this page, and such a function would be useful then.

2022-07-25 02:11 UTC, susheelk approved these changes
LGTM! :slightly_smiling_face: 

Go ahead and merge after resolving these nitpicks. Also could you make another ticket to add the background image to this page? Thanks!

2022-07-25 02:11 UTC, susheelk commented on frontend/src/components/pages/SearchReviews/SearchReviews.tsx
> + * Url Parameters that can be passed in:
(nit) Indent this

2022-07-25 02:11 UTC, susheelk commented on frontend/src/components/pages/SearchReviews/SearchReviews.tsx
> + * search_query: current search command i.e "Potter"
(nit) Double indent these

2022-07-25 02:17 UTC, jessiiepeng commented
> LGTM! 🙂
> 
> Go ahead and merge after resolving these nitpicks. Also could you make another ticket to add the background image to this page? Thanks!

https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=130533dc9d8a462b824114f5d761b348&pm=c
Ticket ^
Should I assign these the adding filtering component / background images tickets to myself?

2022-07-25 03:24 UTC, merged