Creator Frontend + Backend Changes and Stitching
uwblueprint/ccbc pull request #208
Opened 2023-01-30 00:31 UTC by NathanSouphanthong

## Notion ticket link

[Creator Frontend + Backend Changes and stitching](https://www.notion.so/uwblueprintexecs/Creator-Frontend-Backend-Changes-and-stitching-49a45413e4234ff69f8a0f31eb9b4774)

## Implementation description
* Added creator types (Creator, Presentation, Publication, CreatorRequest) in frontend/src/types/CreatorTypes 
* Added updateCreator method in backend + exposed it in route /creators/<id>
* Modified createCreator method to take in only userId
* Added CreatorAPIClient.ts for updateCreator and createCreator functions

## Steps to test

## What should reviewers focus on?
* Updates to createCreator method on backend
* CreatorAPIClient updateCreator, createCreator functions

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have run docker-compose up and my project compiled
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-01-30 00:55 UTC, Shrinjay requested changes
Looking good man, just add logging

2023-01-30 00:55 UTC, Shrinjay commented on frontend/src/APIClients/CreatorAPIClient.ts
> +    return null;
Add some logging for the error case, can be as simple as a console.log.

2023-01-30 00:55 UTC, Shrinjay commented on frontend/src/APIClients/CreatorAPIClient.ts
> +    return null;
Same here, add logging

2023-01-30 01:01 UTC, NathanSouphanthong commented on backend/typescript/services/implementations/creatorService.ts
> +          where: { userId },
Missed this, should be `where: {userId: userId}`

2023-01-30 01:13 UTC, Shrinjay commented
@NathanSouphanthong [video going over backend testing with postman](https://drive.google.com/file/d/1xsFyp_EMogtXipR-AXgiNRAljy20P8h7/view?usp=sharing)

2023-02-02 01:37 UTC, Shrinjay approved these changes

2023-02-02 01:37 UTC, merged