[Feat]: Add admin creator profile tab
uwblueprint/ccbc pull request #212
Opened 2023-02-05 22:17 UTC by khloe-r

## Notion ticket link

[Admin: Admin Dashboard w/o Preview of Profile](https://www.notion.so/uwblueprintexecs/Admin-Admin-Dashboard-w-o-Preview-of-Profile-611760f840914d16acbd7934a5e6c633)

## Implementation description
* Refactored AdminDashboard into tabs for magazine reviews + creator profiles
* Created creatorService API client to get, approve and delete creators
* Small bug fixes for creator routes/migration including adding deleteCreator method

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/75541476/216848872-915dc369-1604-4c08-899c-83b5953b75b9.png">

## Steps to test
1. login with admin account + seeded database
2. visit creator profile tab of admin dashboard, try approving, rejecting or deleting creator

## What should reviewers focus on?
* Delete Creator method (not entirely sure if there's anything else I need to delete or unlink)
* Does Reject have the same effect as deleting a creator?

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have run docker-compose up and my project compiled
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-02-16 01:35 UTC, Shrinjay requested changes
Looking really really good!! Just need to modify the behaviour of the rejection logic.

2023-02-16 01:35 UTC, Shrinjay commented on frontend/src/components/pages/AdminDashboard/AdminCreatorProfiles.tsx
> +                      Reject
So rejection doesn't actually mean deletion, sorry this should've been a lot more clear. The expected behaviour for rejection is to hit a backend route and send an email to the creator. There's no real copy defined for the email so I'd just say make it:
```
Hello {name},

Unfortunately, your creator profile for the Canadian Children's Book Centre creator directory has been declined. We encourage you to check over your profile again and contact us if further assistance is required.

Thanks!
CCBC
```
Their name and email should be a part of the creator model. If they're not populated yet, just don't send an email.

2023-02-17 19:02 UTC, khloe-r commented on backend/typescript/services/implementations/creatorService.ts
> +        Hello ${rejectedUser.first_name},
added rejection logic but ticket is blocked by creator data model, getting TS errors because the properties don't exist yet

2023-02-27 00:51 UTC, Shrinjay requested changes

2023-02-27 00:51 UTC, Shrinjay commented on frontend/src/components/pages/AdminDashboard/AdminCreatorProfiles.tsx
> +                {tableMeta.rowData[5] ? (
name the purpose of this in a variable before the return statement

2023-02-27 02:07 UTC, Shrinjay approved these changes

2023-02-27 02:07 UTC, merged