Not Found Page
uwblueprint/ccbc pull request #34
Opened 2021-12-18 20:32 UTC by r-aya

Created Not Found Page; non-existing URLS redirect here

## Notion ticket link

(Ticket not yet created)
[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)

## Implementation description
* Used SVGs from the Figma and styles from theme file

## Steps to test
1. Go to a non-existent URL

## What should reviewers focus on?
* 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have run docker-compose up and my project compiled
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-12-21 00:48 UTC, chriistine submitted a review, later dismissed
Hey I think you have some merge conflicts and yarn lint errors - are you able to fix those first?

2021-12-31 01:50 UTC, Tayef-Shah commented
This is the ticket for the not found page right? @r-aya 
https://www.notion.so/uwblueprintexecs/404-Page-01a5c7ef96f9452e82a41dbd771fdf34

2022-02-13 19:59 UTC, susheelk requested changes

2022-02-13 19:59 UTC, susheelk commented on frontend/yarn.lock
> -  version "7.16.3"
Hey we decided to not commit yarn.lock files for now. Could you remove this from your PR? Just do `git checkout origin/development yarn.lock`, then commit and push

2022-02-18 22:02 UTC, susheelk approved these changes

2022-02-18 22:47 UTC, susheelk requested changes
Hey, the background image doesn't seem to fill the whole screen. This is what it looks like for me: 
![image](https://user-images.githubusercontent.com/19916973/154771338-c9266efa-a2fa-40e4-bff1-a59c4eef4a75.png)

Could you please look into this? Thanks!

2022-02-20 18:59 UTC, susheelk approved these changes
Good job! Looks good to merge :partying_face:

2022-02-20 20:54 UTC, merged