added invite admin modal
uwblueprint/ccbc pull request #55
Opened 2022-03-09 03:03 UTC by obaranek

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Invite-New-Admin-Flow-0233d07d955442b0b3d7005790dcedcd)

## Implementation description
* implemented Invite New Admin modal

## Steps to test
1. Invited a dummy email through the new invite flow
2. Confirmed that I got a response with a token

## What should reviewers focus on?
* 

## Checklist
- [X] My PR name is descriptive and in imperative tense
- [X] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [X] I have run the appropriate linter(s)
- [X] I have run docker-compose up and my project compiled
- [X] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-09 15:04 UTC, mahadzaryab1 reviewed
added a few small comments

2022-03-09 17:13 UTC, dhmi19 requested changes
Looks good to me, just a small change with the button being disabled if not all fields are set

2022-03-09 17:13 UTC, dhmi19 commented on frontend/src/components/common/InviteAdminModal.tsx
> +            onClick={onSubmitClick}
actually, there is already a field check and since only admins will use this I don't think it's a big deal

2022-03-09 17:14 UTC, dhmi19 approved these changes
lgtm

2022-03-09 23:58 UTC, obaranek commented on frontend/src/components/common/InviteAdminModal.tsx
> +          "Unable to sign up user. Please check entered details.",
@susheelk do we have such a file?

2022-03-09 23:59 UTC, obaranek commented on frontend/src/components/common/InviteAdminModal.tsx
> +};
Are the variable names not clear enough?

2022-03-10 00:00 UTC, dhmi19 commented on frontend/src/components/common/InviteAdminModal.tsx
> +};
I think it's good practise to do so Omar

2022-03-11 02:47 UTC, mahadzaryab1 approved these changes
minor comment - otherwise LGTM!

2022-03-11 02:47 UTC, mahadzaryab1 commented on frontend/src/components/common/InviteAdminModal.tsx
> +  // this describes the state of the modal
the standard is to have these comments start with `/**`

2022-03-11 02:47 UTC, mahadzaryab1 commented on frontend/src/components/common/InviteAdminModal.tsx
> +  // handler function to be executed when the submit button is clicked
same

2022-03-13 19:57 UTC, merged