[Feat] Search Box Component
uwblueprint/ccbc pull request #62
Opened 2022-03-17 00:26 UTC by r-aya

## Notion ticket link

[Search Function: Search Box Component](https://www.notion.so/uwblueprintexecs/Search-Function-Search-Box-Component-107a6b6ffc8a47a18e19b5e07617bfea)

## Implementation description
* Created Search Box component using Chakra's input component and icons

## Steps to test
1. Type into input field
2. Click Search to ensure cursor changes
3. Click left icon to ensure cursor doesn't change
4. Check styling for focus and hover

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have run docker-compose up and my project compiled
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-20 20:57 UTC, hyunzeekim reviewed
code looks good! one minor thing when testing: i noticed that if the search bar is filled with words until the end, then the words behind the "Search" button is cut off and can't be seen even if you try to highlight all the way until the end to scroll.

2022-06-15 22:40 UTC, susheelk requested changes
Code looks good! There's just a requirement that I forgot about lol. Also the deploy job's failing, could you look into that?

2022-06-15 22:40 UTC, susheelk commented on frontend/src/components/pages/SearchBox.tsx
> +const SearchBox = (): React.ReactElement => {
Hey, so this ticket also involves keeping track of the search text as state. I think the previous dev forgot to implement this. Could you:
1. Take a function called `setSearchText` as a prop
2. Upon click of the search button, call this function with the entered search text

Thanks!

2022-06-20 23:59 UTC, susheelk approved these changes
LGTM! Nice work! :tada:

2022-06-21 16:07 UTC, merged