Add migrations
uwblueprint/ccbc pull request #64
Opened 2022-03-17 21:06 UTC by mahadzaryab1

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have run docker-compose up and my project compiled
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-20 14:40 UTC, mahadzaryab1 commented on backend/typescript/config/config.json
> +  "staging": {
this corresponds to the `NODE_ENV` environment variable - we'll need to make sure this is set accordingly in heroku

2022-03-20 14:40 UTC, mahadzaryab1 commented on backend/typescript/Procfile
> +release: npx sequelize-cli db:migrate
for automatic migrations

2022-03-25 02:22 UTC, susheelk requested changes

2022-03-25 02:52 UTC, susheelk approved these changes
Looks good to me, thanks!

2022-03-25 02:58 UTC, merged